# Permalinks
permalink:        pretty

# Setup
title:            YAPDNS
tagline:          'collect, display, correlate and analyze passive dns data'
description:      'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://yapdns.github.io

author:
  name:           'Akshay Aurora'
  url:            https://twitter.com/akshayaurora

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/yapdns/

gems: [jekyll-paginate]
